### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This is a crazy idea.  I want to take the clang/gulp/tsc/lint stuff, and wrap it all into a single npm module that we can share across projects.  We could make it a public thing that others could use too.  This way we're not trying to keep 20 repos up to date.  This is just an initial cut.  Looking for thoughts :)

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@ofrobots @matthewloring @jmdobry @DominicKramer

**Comment by ofrobots** [comment]
This is great! Thanks for putting it together.

One thought: It is great that we no longer have to copy tsconfig.json, tslint.json, .clang-format between repos, but I suspect that it would be a bit too rigid to to force people to a standard gulpfile. I would expect different repos needing to customize the build steps, add new steps etc.

Would there be an easy/consumable way for users to inherit / extend the common gulpfile – or perhaps it can prefer the local gulpfile if present? I am not sure how we would handle the default command set that goots exposes, e.g. if the local gulpfile doesn't have `test.check-format`. Thoughts?

**Comment by JustinBeckwith** [comment]
I had a few thoughts here as well.  I really see 2 options:

1. We could just look at the gulpfile as in implementation detail of goots.  If you want to add/extend your own command - it's really up to you to bring in your own copy of gulp, your own gulpfile, your own commands, etc.  It isn't terribly friendly, but it's unopinionated.  

2. We could emit a d.ts from this repo, and make the gulpfile extensible.  In the consuming library, I could inherit from the base gulpfile, add my own methods, and then have goots start by looking in the user project root for a gulpfile first instead of looking in the npm module directory.

**Comment by ofrobots** [comment]
I think we definitely need 2. For example, we already need to override the gulpfile for dockerized testing in https://github.com/GoogleCloudPlatform/nodejs-docker/pull/99.

Some more thoughts: it should be easy for folks to override (if necessary) tsconfig and tslint – they are json files and `goots` can do `tsconfig = extend({}, defaultTsconfig, localTsConfig);`. One example of where this may be necessary is that some project may not necessarily want to target es5.

**Comment by DominicKramer** [comment]
I agree that we need #2. In transitioning projects to Typescript is seems very common to need a customized gulpfile.  Also, some projects might want to use (or are currently using) mocha instead of Ava.

**Pull request merged**
